Update force-fail.yml

diff --git a/.github/workflows/force-fail.yml b/.github/workflows/force-fail.yml
--- a/.github/workflows/force-fail.yml
+++ b/.github/workflows/force-fail.yml
@@ -6,5 +6,8 @@ jobs:
   fail:
     runs-on: ubuntu-latest
     steps:
-      - name: Fail intentionally
-        run: exit 1
+      - name: This will fail
+        run: |
+          echo "failing now"
+          exit 1
+        shell: bash
